[package]
name = "over/matter-plataformer"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Matter = "evaera/matter@0.5.2"
Rewire = "sayhisam1/rewire@0.3.0"
Knit = "sleitnick/knit@1.4.7"
Plasma = "evaera/plasma@0.3.0"
